/// Script-generated.

import {BuiltTimeDom} from '../BuiltTimeDom'

/**
 * Map from HTML tag names to their corresponding built-time types.
 */
export interface BuiltTimeHtmlTypesMap {
    a: BuiltTimeDom.HTMLAnchorElement
    abbr: BuiltTimeDom.HTMLElement
    address: BuiltTimeDom.HTMLElement
    area: BuiltTimeDom.HTMLAreaElement
    article: BuiltTimeDom.HTMLElement
    aside: BuiltTimeDom.HTMLElement
    audio: BuiltTimeDom.HTMLAudioElement
    b: BuiltTimeDom.HTMLElement
    base: BuiltTimeDom.HTMLBaseElement
    bdi: BuiltTimeDom.HTMLElement
    bdo: BuiltTimeDom.HTMLElement
    blockquote: BuiltTimeDom.HTMLQuoteElement
    body: BuiltTimeDom.HTMLBodyElement
    br: BuiltTimeDom.HTMLBRElement
    button: BuiltTimeDom.HTMLButtonElement
    canvas: BuiltTimeDom.HTMLCanvasElement
    caption: BuiltTimeDom.HTMLTableCaptionElement
    cite: BuiltTimeDom.HTMLElement
    code: BuiltTimeDom.HTMLElement
    col: BuiltTimeDom.HTMLTableColElement
    colgroup: BuiltTimeDom.HTMLTableColElement
    data: BuiltTimeDom.HTMLDataElement
    datalist: BuiltTimeDom.HTMLDataListElement
    dd: BuiltTimeDom.HTMLElement
    del: BuiltTimeDom.HTMLModElement
    details: BuiltTimeDom.HTMLDetailsElement
    dfn: BuiltTimeDom.HTMLElement
    dialog: BuiltTimeDom.HTMLDialogElement
    div: BuiltTimeDom.HTMLDivElement
    dl: BuiltTimeDom.HTMLDListElement
    dt: BuiltTimeDom.HTMLElement
    em: BuiltTimeDom.HTMLElement
    embed: BuiltTimeDom.HTMLEmbedElement
    fieldset: BuiltTimeDom.HTMLFieldSetElement
    figcaption: BuiltTimeDom.HTMLElement
    figure: BuiltTimeDom.HTMLElement
    footer: BuiltTimeDom.HTMLElement
    form: BuiltTimeDom.HTMLFormElement
    h1: BuiltTimeDom.HTMLHeadingElement
    h2: BuiltTimeDom.HTMLHeadingElement
    h3: BuiltTimeDom.HTMLHeadingElement
    h4: BuiltTimeDom.HTMLHeadingElement
    h5: BuiltTimeDom.HTMLHeadingElement
    h6: BuiltTimeDom.HTMLHeadingElement
    head: BuiltTimeDom.HTMLHeadElement
    header: BuiltTimeDom.HTMLElement
    hr: BuiltTimeDom.HTMLHRElement
    html: BuiltTimeDom.HTMLHtmlElement
    i: BuiltTimeDom.HTMLElement
    iframe: BuiltTimeDom.HTMLIFrameElement
    img: BuiltTimeDom.HTMLImageElement
    input: BuiltTimeDom.HTMLInputElement
    ins: BuiltTimeDom.HTMLModElement
    kbd: BuiltTimeDom.HTMLElement
    label: BuiltTimeDom.HTMLLabelElement
    legend: BuiltTimeDom.HTMLLegendElement
    li: BuiltTimeDom.HTMLLIElement
    link: BuiltTimeDom.HTMLLinkElement
    main: BuiltTimeDom.HTMLElement
    map: BuiltTimeDom.HTMLMapElement
    mark: BuiltTimeDom.HTMLElement
    meta: BuiltTimeDom.HTMLMetaElement
    meter: BuiltTimeDom.HTMLMeterElement
    nav: BuiltTimeDom.HTMLElement
    noscript: BuiltTimeDom.HTMLElement
    object: BuiltTimeDom.HTMLObjectElement
    ol: BuiltTimeDom.HTMLOListElement
    optgroup: BuiltTimeDom.HTMLOptGroupElement
    option: BuiltTimeDom.HTMLOptionElement
    output: BuiltTimeDom.HTMLOutputElement
    p: BuiltTimeDom.HTMLParagraphElement
    param: BuiltTimeDom.HTMLParamElement
    picture: BuiltTimeDom.HTMLPictureElement
    pre: BuiltTimeDom.HTMLPreElement
    progress: BuiltTimeDom.HTMLProgressElement
    q: BuiltTimeDom.HTMLQuoteElement
    rb: BuiltTimeDom.HTMLElement
    rp: BuiltTimeDom.HTMLElement
    rt: BuiltTimeDom.HTMLElement
    rtc: BuiltTimeDom.HTMLElement
    ruby: BuiltTimeDom.HTMLElement
    s: BuiltTimeDom.HTMLElement
    samp: BuiltTimeDom.HTMLElement
    script: BuiltTimeDom.HTMLScriptElement
    section: BuiltTimeDom.HTMLElement
    select: BuiltTimeDom.HTMLSelectElement
    small: BuiltTimeDom.HTMLElement
    source: BuiltTimeDom.HTMLSourceElement
    span: BuiltTimeDom.HTMLSpanElement
    strong: BuiltTimeDom.HTMLElement
    style: BuiltTimeDom.HTMLStyleElement
    sub: BuiltTimeDom.HTMLElement
    summary: BuiltTimeDom.HTMLElement
    sup: BuiltTimeDom.HTMLElement
    table: BuiltTimeDom.HTMLTableElement
    tbody: BuiltTimeDom.HTMLTableSectionElement
    td: BuiltTimeDom.HTMLTableDataCellElement
    template: BuiltTimeDom.HTMLTemplateElement
    textarea: BuiltTimeDom.HTMLTextAreaElement
    tfoot: BuiltTimeDom.HTMLTableSectionElement
    th: BuiltTimeDom.HTMLTableHeaderCellElement
    thead: BuiltTimeDom.HTMLTableSectionElement
    time: BuiltTimeDom.HTMLTimeElement
    title: BuiltTimeDom.HTMLTitleElement
    tr: BuiltTimeDom.HTMLTableRowElement
    track: BuiltTimeDom.HTMLTrackElement
    u: BuiltTimeDom.HTMLElement
    ul: BuiltTimeDom.HTMLUListElement
    var: BuiltTimeDom.HTMLElement
    video: BuiltTimeDom.HTMLVideoElement
    wbr: BuiltTimeDom.HTMLElement
}
