/// Script-generated.

import {HtmlTypesMap} from './HtmlTypesMap'

/**
 * Content categories for HTML elements. For reference, see:
 * https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories.
 */
export namespace HtmlContent {
    export type TransparentContent = HTMLElement | SVGSVGElement | Text
    export type MetadataContent = HtmlTypesMap['base'] | HtmlTypesMap['link'] | HtmlTypesMap['meta'] | HtmlTypesMap['noscript'] | HtmlTypesMap['script'] | HtmlTypesMap['style'] | HtmlTypesMap['template'] | HtmlTypesMap['title']
    export type FlowContent = HtmlTypesMap['a'] | HtmlTypesMap['abbr'] | HtmlTypesMap['address'] | HtmlTypesMap['article'] | HtmlTypesMap['aside'] | HtmlTypesMap['audio'] | HtmlTypesMap['b'] | HtmlTypesMap['bdi'] | HtmlTypesMap['bdo'] | HtmlTypesMap['blockquote'] | HtmlTypesMap['br'] | HtmlTypesMap['button'] | HtmlTypesMap['canvas'] | HtmlTypesMap['cite'] | HtmlTypesMap['code'] | HtmlTypesMap['data'] | HtmlTypesMap['datalist'] | HtmlTypesMap['del'] | HtmlTypesMap['details'] | HtmlTypesMap['dfn'] | HtmlTypesMap['dialog'] | HtmlTypesMap['div'] | HtmlTypesMap['dl'] | HtmlTypesMap['em'] | HtmlTypesMap['embed'] | HtmlTypesMap['fieldset'] | HtmlTypesMap['figure'] | HtmlTypesMap['footer'] | HtmlTypesMap['form'] | HtmlTypesMap['h1'] | HtmlTypesMap['h2'] | HtmlTypesMap['h3'] | HtmlTypesMap['h4'] | HtmlTypesMap['h5'] | HtmlTypesMap['h6'] | HtmlTypesMap['header'] | HtmlTypesMap['hr'] | HtmlTypesMap['i'] | HtmlTypesMap['iframe'] | HtmlTypesMap['img'] | HtmlTypesMap['input'] | HtmlTypesMap['ins'] | HtmlTypesMap['kbd'] | HtmlTypesMap['label'] | HtmlTypesMap['main'] | HtmlTypesMap['map'] | HtmlTypesMap['mark'] | HtmlTypesMap['meter'] | HtmlTypesMap['nav'] | HtmlTypesMap['noscript'] | HtmlTypesMap['object'] | HtmlTypesMap['ol'] | HtmlTypesMap['output'] | HtmlTypesMap['p'] | HtmlTypesMap['pre'] | HtmlTypesMap['progress'] | HtmlTypesMap['q'] | HtmlTypesMap['ruby'] | HtmlTypesMap['s'] | HtmlTypesMap['samp'] | HtmlTypesMap['script'] | HtmlTypesMap['section'] | HtmlTypesMap['select'] | HtmlTypesMap['small'] | HtmlTypesMap['span'] | HtmlTypesMap['strong'] | HtmlTypesMap['sub'] | HtmlTypesMap['sup'] | SVGSVGElement | HtmlTypesMap['table'] | HtmlTypesMap['template'] | HtmlTypesMap['textarea'] | HtmlTypesMap['time'] | HtmlTypesMap['u'] | HtmlTypesMap['ul'] | HtmlTypesMap['var'] | HtmlTypesMap['video'] | HtmlTypesMap['wbr'] | Text | HtmlTypesMap['area'] | HtmlTypesMap['link']
    export type SectioningContent = HtmlTypesMap['article'] | HtmlTypesMap['aside'] | HtmlTypesMap['nav'] | HtmlTypesMap['section']
    export type HeadingContent = HtmlTypesMap['h1'] | HtmlTypesMap['h2'] | HtmlTypesMap['h3'] | HtmlTypesMap['h4'] | HtmlTypesMap['h5'] | HtmlTypesMap['h6']
    export type PhrasingContent = HtmlTypesMap['a'] | HtmlTypesMap['abbr'] | HtmlTypesMap['audio'] | HtmlTypesMap['b'] | HtmlTypesMap['bdi'] | HtmlTypesMap['bdo'] | HtmlTypesMap['br'] | HtmlTypesMap['button'] | HtmlTypesMap['canvas'] | HtmlTypesMap['cite'] | HtmlTypesMap['code'] | HtmlTypesMap['data'] | HtmlTypesMap['datalist'] | HtmlTypesMap['del'] | HtmlTypesMap['dfn'] | HtmlTypesMap['em'] | HtmlTypesMap['embed'] | HtmlTypesMap['i'] | HtmlTypesMap['iframe'] | HtmlTypesMap['img'] | HtmlTypesMap['input'] | HtmlTypesMap['ins'] | HtmlTypesMap['kbd'] | HtmlTypesMap['label'] | HtmlTypesMap['map'] | HtmlTypesMap['mark'] | HtmlTypesMap['meter'] | HtmlTypesMap['noscript'] | HtmlTypesMap['object'] | HtmlTypesMap['output'] | HtmlTypesMap['progress'] | HtmlTypesMap['q'] | HtmlTypesMap['ruby'] | HtmlTypesMap['s'] | HtmlTypesMap['samp'] | HtmlTypesMap['script'] | HtmlTypesMap['select'] | HtmlTypesMap['small'] | HtmlTypesMap['span'] | HtmlTypesMap['strong'] | HtmlTypesMap['sub'] | HtmlTypesMap['sup'] | SVGSVGElement | HtmlTypesMap['template'] | HtmlTypesMap['textarea'] | HtmlTypesMap['time'] | HtmlTypesMap['u'] | HtmlTypesMap['var'] | HtmlTypesMap['video'] | HtmlTypesMap['wbr'] | Text | HtmlTypesMap['area'] | HtmlTypesMap['link']
    export type EmbeddedContent = HtmlTypesMap['audio'] | HtmlTypesMap['canvas'] | HtmlTypesMap['embed'] | HtmlTypesMap['iframe'] | HtmlTypesMap['img'] | HtmlTypesMap['object'] | SVGSVGElement | HtmlTypesMap['video']
    export type InteractiveContent = HtmlTypesMap['button'] | HtmlTypesMap['details'] | HtmlTypesMap['embed'] | HtmlTypesMap['iframe'] | HtmlTypesMap['label'] | HtmlTypesMap['select'] | HtmlTypesMap['textarea'] | HtmlTypesMap['a'] | HtmlTypesMap['audio'] | HtmlTypesMap['img'] | HtmlTypesMap['input'] | HtmlTypesMap['video']
    export type SectioningRoots = HtmlTypesMap['blockquote'] | HtmlTypesMap['body'] | HtmlTypesMap['details'] | HtmlTypesMap['dialog'] | HtmlTypesMap['fieldset'] | HtmlTypesMap['figure'] | HtmlTypesMap['td']
    export type FormAssociatedElements = HtmlTypesMap['button'] | HtmlTypesMap['fieldset'] | HtmlTypesMap['input'] | HtmlTypesMap['label'] | HtmlTypesMap['object'] | HtmlTypesMap['output'] | HtmlTypesMap['select'] | HtmlTypesMap['textarea'] | HtmlTypesMap['img']
    export type ListedElements = HtmlTypesMap['button'] | HtmlTypesMap['fieldset'] | HtmlTypesMap['input'] | HtmlTypesMap['object'] | HtmlTypesMap['output'] | HtmlTypesMap['select'] | HtmlTypesMap['textarea']
    export type SubmittableElements = HtmlTypesMap['button'] | HtmlTypesMap['input'] | HtmlTypesMap['object'] | HtmlTypesMap['select'] | HtmlTypesMap['textarea']
    export type ResettableElements = HtmlTypesMap['input'] | HtmlTypesMap['output'] | HtmlTypesMap['select'] | HtmlTypesMap['textarea']
    export type LabelableElements = HtmlTypesMap['button'] | HtmlTypesMap['input'] | HtmlTypesMap['meter'] | HtmlTypesMap['output'] | HtmlTypesMap['progress'] | HtmlTypesMap['select'] | HtmlTypesMap['textarea']
    export type ReassociateableElements = HtmlTypesMap['button'] | HtmlTypesMap['fieldset'] | HtmlTypesMap['input'] | HtmlTypesMap['label'] | HtmlTypesMap['object'] | HtmlTypesMap['output'] | HtmlTypesMap['select'] | HtmlTypesMap['textarea']
    export type PalpableContent = HtmlTypesMap['a'] | HtmlTypesMap['abbr'] | HtmlTypesMap['address'] | HtmlTypesMap['article'] | HtmlTypesMap['aside'] | HtmlTypesMap['b'] | HtmlTypesMap['bdi'] | HtmlTypesMap['bdo'] | HtmlTypesMap['blockquote'] | HtmlTypesMap['button'] | HtmlTypesMap['canvas'] | HtmlTypesMap['cite'] | HtmlTypesMap['code'] | HtmlTypesMap['data'] | HtmlTypesMap['details'] | HtmlTypesMap['dfn'] | HtmlTypesMap['div'] | HtmlTypesMap['em'] | HtmlTypesMap['embed'] | HtmlTypesMap['fieldset'] | HtmlTypesMap['figure'] | HtmlTypesMap['footer'] | HtmlTypesMap['form'] | HtmlTypesMap['h1'] | HtmlTypesMap['h2'] | HtmlTypesMap['h3'] | HtmlTypesMap['h4'] | HtmlTypesMap['h5'] | HtmlTypesMap['h6'] | HtmlTypesMap['header'] | HtmlTypesMap['i'] | HtmlTypesMap['iframe'] | HtmlTypesMap['img'] | HtmlTypesMap['ins'] | HtmlTypesMap['kbd'] | HtmlTypesMap['label'] | HtmlTypesMap['main'] | HtmlTypesMap['map'] | HtmlTypesMap['mark'] | HtmlTypesMap['meter'] | HtmlTypesMap['nav'] | HtmlTypesMap['object'] | HtmlTypesMap['output'] | HtmlTypesMap['p'] | HtmlTypesMap['pre'] | HtmlTypesMap['progress'] | HtmlTypesMap['q'] | HtmlTypesMap['ruby'] | HtmlTypesMap['s'] | HtmlTypesMap['samp'] | HtmlTypesMap['section'] | HtmlTypesMap['select'] | HtmlTypesMap['small'] | HtmlTypesMap['span'] | HtmlTypesMap['strong'] | HtmlTypesMap['sub'] | HtmlTypesMap['sup'] | SVGSVGElement | HtmlTypesMap['table'] | HtmlTypesMap['textarea'] | HtmlTypesMap['time'] | HtmlTypesMap['u'] | HtmlTypesMap['var'] | HtmlTypesMap['video'] | HtmlTypesMap['audio'] | HtmlTypesMap['dl'] | HtmlTypesMap['input'] | HtmlTypesMap['ol'] | HtmlTypesMap['ul'] | Text
    export type ScriptSupportingElements = HtmlTypesMap['script'] | HtmlTypesMap['template']
}
