/// Script-generated.

/**
 * Content categories for HTML elements. For reference, see:
 * https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories.
 */
export namespace HTMLElementContent {
    export type TransparentContent = string | HTMLElement | SVGSVGElement
    export type MetadataContent = HTMLElementTagNameMap['base'] | HTMLElementTagNameMap['link'] | HTMLElementTagNameMap['meta'] | HTMLElementTagNameMap['noscript'] | HTMLElementTagNameMap['script'] | HTMLElementTagNameMap['style'] | HTMLElementTagNameMap['template'] | HTMLElementTagNameMap['title']
    export type FlowContent = HTMLElementTagNameMap['a'] | HTMLElementTagNameMap['abbr'] | HTMLElementTagNameMap['address'] | HTMLElementTagNameMap['article'] | HTMLElementTagNameMap['aside'] | HTMLElementTagNameMap['audio'] | HTMLElementTagNameMap['b'] | HTMLElementTagNameMap['bdi'] | HTMLElementTagNameMap['bdo'] | HTMLElementTagNameMap['blockquote'] | HTMLElementTagNameMap['br'] | HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['canvas'] | HTMLElementTagNameMap['cite'] | HTMLElementTagNameMap['code'] | HTMLElementTagNameMap['data'] | HTMLElementTagNameMap['datalist'] | HTMLElementTagNameMap['del'] | HTMLElementTagNameMap['details'] | HTMLElementTagNameMap['dfn'] | HTMLElementTagNameMap['dialog'] | HTMLElementTagNameMap['div'] | HTMLElementTagNameMap['dl'] | HTMLElementTagNameMap['em'] | HTMLElementTagNameMap['embed'] | HTMLElementTagNameMap['fieldset'] | HTMLElementTagNameMap['figure'] | HTMLElementTagNameMap['footer'] | HTMLElementTagNameMap['form'] | HTMLElementTagNameMap['h1'] | HTMLElementTagNameMap['h2'] | HTMLElementTagNameMap['h3'] | HTMLElementTagNameMap['h4'] | HTMLElementTagNameMap['h5'] | HTMLElementTagNameMap['h6'] | HTMLElementTagNameMap['header'] | HTMLElementTagNameMap['hr'] | HTMLElementTagNameMap['i'] | HTMLElementTagNameMap['iframe'] | HTMLElementTagNameMap['img'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['ins'] | HTMLElementTagNameMap['kbd'] | HTMLElementTagNameMap['label'] | HTMLElementTagNameMap['main'] | HTMLElementTagNameMap['map'] | HTMLElementTagNameMap['mark'] | HTMLElementTagNameMap['meter'] | HTMLElementTagNameMap['nav'] | HTMLElementTagNameMap['noscript'] | HTMLElementTagNameMap['object'] | HTMLElementTagNameMap['ol'] | HTMLElementTagNameMap['output'] | HTMLElementTagNameMap['p'] | HTMLElementTagNameMap['pre'] | HTMLElementTagNameMap['progress'] | HTMLElementTagNameMap['q'] | HTMLElementTagNameMap['ruby'] | HTMLElementTagNameMap['s'] | HTMLElementTagNameMap['samp'] | HTMLElementTagNameMap['script'] | HTMLElementTagNameMap['section'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['small'] | HTMLElementTagNameMap['span'] | HTMLElementTagNameMap['strong'] | HTMLElementTagNameMap['sub'] | HTMLElementTagNameMap['sup'] | SVGSVGElement | HTMLElementTagNameMap['table'] | HTMLElementTagNameMap['template'] | HTMLElementTagNameMap['textarea'] | HTMLElementTagNameMap['time'] | HTMLElementTagNameMap['u'] | HTMLElementTagNameMap['ul'] | HTMLElementTagNameMap['var'] | HTMLElementTagNameMap['video'] | HTMLElementTagNameMap['wbr'] | string | HTMLElementTagNameMap['area'] | HTMLElementTagNameMap['link']
    export type SectioningContent = HTMLElementTagNameMap['article'] | HTMLElementTagNameMap['aside'] | HTMLElementTagNameMap['nav'] | HTMLElementTagNameMap['section']
    export type HeadingContent = HTMLElementTagNameMap['h1'] | HTMLElementTagNameMap['h2'] | HTMLElementTagNameMap['h3'] | HTMLElementTagNameMap['h4'] | HTMLElementTagNameMap['h5'] | HTMLElementTagNameMap['h6']
    export type PhrasingContent = HTMLElementTagNameMap['a'] | HTMLElementTagNameMap['abbr'] | HTMLElementTagNameMap['audio'] | HTMLElementTagNameMap['b'] | HTMLElementTagNameMap['bdi'] | HTMLElementTagNameMap['bdo'] | HTMLElementTagNameMap['br'] | HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['canvas'] | HTMLElementTagNameMap['cite'] | HTMLElementTagNameMap['code'] | HTMLElementTagNameMap['data'] | HTMLElementTagNameMap['datalist'] | HTMLElementTagNameMap['del'] | HTMLElementTagNameMap['dfn'] | HTMLElementTagNameMap['em'] | HTMLElementTagNameMap['embed'] | HTMLElementTagNameMap['i'] | HTMLElementTagNameMap['iframe'] | HTMLElementTagNameMap['img'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['ins'] | HTMLElementTagNameMap['kbd'] | HTMLElementTagNameMap['label'] | HTMLElementTagNameMap['map'] | HTMLElementTagNameMap['mark'] | HTMLElementTagNameMap['meter'] | HTMLElementTagNameMap['noscript'] | HTMLElementTagNameMap['object'] | HTMLElementTagNameMap['output'] | HTMLElementTagNameMap['progress'] | HTMLElementTagNameMap['q'] | HTMLElementTagNameMap['ruby'] | HTMLElementTagNameMap['s'] | HTMLElementTagNameMap['samp'] | HTMLElementTagNameMap['script'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['small'] | HTMLElementTagNameMap['span'] | HTMLElementTagNameMap['strong'] | HTMLElementTagNameMap['sub'] | HTMLElementTagNameMap['sup'] | SVGSVGElement | HTMLElementTagNameMap['template'] | HTMLElementTagNameMap['textarea'] | HTMLElementTagNameMap['time'] | HTMLElementTagNameMap['u'] | HTMLElementTagNameMap['var'] | HTMLElementTagNameMap['video'] | HTMLElementTagNameMap['wbr'] | string | HTMLElementTagNameMap['area'] | HTMLElementTagNameMap['link']
    export type EmbeddedContent = HTMLElementTagNameMap['audio'] | HTMLElementTagNameMap['canvas'] | HTMLElementTagNameMap['embed'] | HTMLElementTagNameMap['iframe'] | HTMLElementTagNameMap['img'] | HTMLElementTagNameMap['object'] | SVGSVGElement | HTMLElementTagNameMap['video']
    export type InteractiveContent = HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['details'] | HTMLElementTagNameMap['embed'] | HTMLElementTagNameMap['iframe'] | HTMLElementTagNameMap['label'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['textarea'] | HTMLElementTagNameMap['a'] | HTMLElementTagNameMap['audio'] | HTMLElementTagNameMap['img'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['video']
    export type SectioningRoots = HTMLElementTagNameMap['blockquote'] | HTMLElementTagNameMap['body'] | HTMLElementTagNameMap['details'] | HTMLElementTagNameMap['dialog'] | HTMLElementTagNameMap['fieldset'] | HTMLElementTagNameMap['figure'] | HTMLElementTagNameMap['td']
    export type FormAssociatedElements = HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['fieldset'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['label'] | HTMLElementTagNameMap['object'] | HTMLElementTagNameMap['output'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['textarea'] | HTMLElementTagNameMap['img']
    export type ListedElements = HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['fieldset'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['object'] | HTMLElementTagNameMap['output'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['textarea']
    export type SubmittableElements = HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['object'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['textarea']
    export type ResettableElements = HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['output'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['textarea']
    export type LabelableElements = HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['meter'] | HTMLElementTagNameMap['output'] | HTMLElementTagNameMap['progress'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['textarea']
    export type ReassociateableElements = HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['fieldset'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['label'] | HTMLElementTagNameMap['object'] | HTMLElementTagNameMap['output'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['textarea']
    export type PalpableContent = HTMLElementTagNameMap['a'] | HTMLElementTagNameMap['abbr'] | HTMLElementTagNameMap['address'] | HTMLElementTagNameMap['article'] | HTMLElementTagNameMap['aside'] | HTMLElementTagNameMap['b'] | HTMLElementTagNameMap['bdi'] | HTMLElementTagNameMap['bdo'] | HTMLElementTagNameMap['blockquote'] | HTMLElementTagNameMap['button'] | HTMLElementTagNameMap['canvas'] | HTMLElementTagNameMap['cite'] | HTMLElementTagNameMap['code'] | HTMLElementTagNameMap['data'] | HTMLElementTagNameMap['details'] | HTMLElementTagNameMap['dfn'] | HTMLElementTagNameMap['div'] | HTMLElementTagNameMap['em'] | HTMLElementTagNameMap['embed'] | HTMLElementTagNameMap['fieldset'] | HTMLElementTagNameMap['figure'] | HTMLElementTagNameMap['footer'] | HTMLElementTagNameMap['form'] | HTMLElementTagNameMap['h1'] | HTMLElementTagNameMap['h2'] | HTMLElementTagNameMap['h3'] | HTMLElementTagNameMap['h4'] | HTMLElementTagNameMap['h5'] | HTMLElementTagNameMap['h6'] | HTMLElementTagNameMap['header'] | HTMLElementTagNameMap['i'] | HTMLElementTagNameMap['iframe'] | HTMLElementTagNameMap['img'] | HTMLElementTagNameMap['ins'] | HTMLElementTagNameMap['kbd'] | HTMLElementTagNameMap['label'] | HTMLElementTagNameMap['main'] | HTMLElementTagNameMap['map'] | HTMLElementTagNameMap['mark'] | HTMLElementTagNameMap['meter'] | HTMLElementTagNameMap['nav'] | HTMLElementTagNameMap['object'] | HTMLElementTagNameMap['output'] | HTMLElementTagNameMap['p'] | HTMLElementTagNameMap['pre'] | HTMLElementTagNameMap['progress'] | HTMLElementTagNameMap['q'] | HTMLElementTagNameMap['ruby'] | HTMLElementTagNameMap['s'] | HTMLElementTagNameMap['samp'] | HTMLElementTagNameMap['section'] | HTMLElementTagNameMap['select'] | HTMLElementTagNameMap['small'] | HTMLElementTagNameMap['span'] | HTMLElementTagNameMap['strong'] | HTMLElementTagNameMap['sub'] | HTMLElementTagNameMap['sup'] | SVGSVGElement | HTMLElementTagNameMap['table'] | HTMLElementTagNameMap['textarea'] | HTMLElementTagNameMap['time'] | HTMLElementTagNameMap['u'] | HTMLElementTagNameMap['var'] | HTMLElementTagNameMap['video'] | HTMLElementTagNameMap['audio'] | HTMLElementTagNameMap['dl'] | HTMLElementTagNameMap['input'] | HTMLElementTagNameMap['ol'] | HTMLElementTagNameMap['ul'] | string
    export type ScriptSupportingElements = HTMLElementTagNameMap['script'] | HTMLElementTagNameMap['template']
}
