/// Script-generated.

export type AriaRole
    = 'alert'
    | 'alertdialog'
    | 'application'
    | 'article'
    | 'banner'
    | 'button'
    | 'cell'
    | 'checkbox'
    | 'columnheader'
    | 'combobox'
    | 'complementary'
    | 'contentinfo'
    | 'definition'
    | 'dialog'
    | 'directory'
    | 'document'
    | 'feed'
    | 'figure'
    | 'form'
    | 'grid'
    | 'gridcell'
    | 'group'
    | 'heading'
    | 'img'
    | 'link'
    | 'list'
    | 'listbox'
    | 'listitem'
    | 'log'
    | 'main'
    | 'marquee'
    | 'math'
    | 'menu'
    | 'menubar'
    | 'menuitem'
    | 'menuitemcheckbox'
    | 'menuitemradio'
    | 'navigation'
    | 'none'
    | 'note'
    | 'option'
    | 'presentation'
    | 'progressbar'
    | 'radio'
    | 'radiogroup'
    | 'region'
    | 'row'
    | 'rowgroup'
    | 'rowheader'
    | 'scrollbar'
    | 'search'
    | 'searchbox'
    | 'separator'
    | 'slider'
    | 'spinbutton'
    | 'status'
    | 'switch'
    | 'tab'
    | 'table'
    | 'tablist'
    | 'tabpanel'
    | 'term'
    | 'textbox'
    | 'timer'
    | 'toolbar'
    | 'tooltip'
    | 'tree'
    | 'treegrid'
    | 'treeitem'

export interface AriaAttributes {
    role?: AriaRole
    'aria-activedescendant'?: string
    'aria-atomic'?: string
    'aria-autocomplete'?: string
    'aria-busy'?: string
    'aria-checked'?: string
    'aria-colcount'?: string
    'aria-colindex'?: string
    'aria-colspan'?: string
    'aria-controls'?: string
    'aria-current'?: string
    'aria-describedby'?: string
    'aria-details'?: string
    'aria-disabled'?: string
    'aria-dropeffect'?: string
    'aria-errormessage'?: string
    'aria-expanded'?: string
    'aria-flowto'?: string
    'aria-grabbed'?: string
    'aria-haspopup'?: string
    'aria-hidden'?: string
    'aria-invalid'?: string
    'aria-keyshortcuts'?: string
    'aria-label'?: string
    'aria-labelledby'?: string
    'aria-level'?: string
    'aria-live'?: string
    'aria-modal'?: string
    'aria-multiline'?: string
    'aria-multiselectable'?: string
    'aria-orientation'?: string
    'aria-owns'?: string
    'aria-placeholder'?: string
    'aria-posinset'?: string
    'aria-pressed'?: string
    'aria-readonly'?: string
    'aria-relevant'?: string
    'aria-required'?: string
    'aria-roledescription'?: string
    'aria-rowcount'?: string
    'aria-rowindex'?: string
    'aria-rowspan'?: string
    'aria-selected'?: string
    'aria-setsize'?: string
    'aria-sort'?: string
    'aria-valuemax'?: string
    'aria-valuemin'?: string
    'aria-valuenow'?: string
    'aria-valuetext'?: string
}
