import {h} from './h'

export interface HtmlTypes {
    a: h.A
    abbr: h.Abbr
    address: h.Address
    applet: h.Applet
    area: h.Area
    article: h.Article
    aside: h.Aside
    audio: h.Audio
    b: h.B
    base: h.Base
    basefont: h.Basefont
    bdi: h.Bdi
    bdo: h.Bdo
    blockquote: h.Blockquote
    body: h.Body
    br: h.Br
    button: h.Button
    canvas: h.Canvas
    caption: h.Caption
    cite: h.Cite
    code: h.Code
    col: h.Col
    colgroup: h.Colgroup
    data: h.Data
    datalist: h.Datalist
    dd: h.Dd
    del: h.Del
    details: h.Details
    dfn: h.Dfn
    dialog: h.Dialog
    dir: h.Dir
    div: h.Div
    dl: h.Dl
    dt: h.Dt
    em: h.Em
    embed: h.Embed
    fieldset: h.Fieldset
    figcaption: h.Figcaption
    figure: h.Figure
    font: h.Font
    footer: h.Footer
    form: h.Form
    frame: h.Frame
    frameset: h.Frameset
    h1: h.H1
    h2: h.H2
    h3: h.H3
    h4: h.H4
    h5: h.H5
    h6: h.H6
    head: h.Head
    header: h.Header
    hgroup: h.Hgroup
    hr: h.Hr
    html: h.Html
    i: h.I
    iframe: h.Iframe
    img: h.Img
    input: h.Input
    ins: h.Ins
    kbd: h.Kbd
    label: h.Label
    legend: h.Legend
    li: h.Li
    link: h.Link
    main: h.Main
    map: h.Map
    mark: h.Mark
    marquee: h.Marquee
    menu: h.Menu
    meta: h.Meta
    meter: h.Meter
    nav: h.Nav
    noscript: h.Noscript
    object: h.Object
    ol: h.Ol
    optgroup: h.Optgroup
    option: h.Option
    output: h.Output
    p: h.P
    param: h.Param
    picture: h.Picture
    pre: h.Pre
    progress: h.Progress
    q: h.Q
    rb: h.Rb
    rp: h.Rp
    rt: h.Rt
    rtc: h.Rtc
    ruby: h.Ruby
    s: h.S
    samp: h.Samp
    script: h.Script
    section: h.Section
    select: h.Select
    slot: h.Slot
    small: h.Small
    source: h.Source
    span: h.Span
    strong: h.Strong
    style: h.Style
    sub: h.Sub
    summary: h.Summary
    sup: h.Sup
    table: h.Table
    tbody: h.Tbody
    td: h.Td
    template: h.Template
    textarea: h.Textarea
    tfoot: h.Tfoot
    th: h.Th
    thead: h.Thead
    time: h.Time
    title: h.Title
    tr: h.Tr
    track: h.Track
    u: h.U
    ul: h.Ul
    var: h.Var
    video: h.Video
    wbr: h.Wbr
}
