/// Script-generated.

import {HtmlTypes} from './HtmlTypes'

/**
 * Content categories for HTML elements. For reference, see:
 * https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories.
 */
export namespace HtmlContent {
    export type TransparentContent = string | HTMLElement | SVGSVGElement
    export type MetadataContent = HtmlTypes['base'] | HtmlTypes['link'] | HtmlTypes['meta'] | HtmlTypes['noscript'] | HtmlTypes['script'] | HtmlTypes['style'] | HtmlTypes['template'] | HtmlTypes['title']
    export type FlowContent = HtmlTypes['a'] | HtmlTypes['abbr'] | HtmlTypes['address'] | HtmlTypes['article'] | HtmlTypes['aside'] | HtmlTypes['audio'] | HtmlTypes['b'] | HtmlTypes['bdi'] | HtmlTypes['bdo'] | HtmlTypes['blockquote'] | HtmlTypes['br'] | HtmlTypes['button'] | HtmlTypes['canvas'] | HtmlTypes['cite'] | HtmlTypes['code'] | HtmlTypes['data'] | HtmlTypes['datalist'] | HtmlTypes['del'] | HtmlTypes['details'] | HtmlTypes['dfn'] | HtmlTypes['dialog'] | HtmlTypes['div'] | HtmlTypes['dl'] | HtmlTypes['em'] | HtmlTypes['embed'] | HtmlTypes['fieldset'] | HtmlTypes['figure'] | HtmlTypes['footer'] | HtmlTypes['form'] | HtmlTypes['h1'] | HtmlTypes['h2'] | HtmlTypes['h3'] | HtmlTypes['h4'] | HtmlTypes['h5'] | HtmlTypes['h6'] | HtmlTypes['header'] | HtmlTypes['hr'] | HtmlTypes['i'] | HtmlTypes['iframe'] | HtmlTypes['img'] | HtmlTypes['input'] | HtmlTypes['ins'] | HtmlTypes['kbd'] | HtmlTypes['label'] | HtmlTypes['main'] | HtmlTypes['map'] | HtmlTypes['mark'] | HtmlTypes['meter'] | HtmlTypes['nav'] | HtmlTypes['noscript'] | HtmlTypes['object'] | HtmlTypes['ol'] | HtmlTypes['output'] | HtmlTypes['p'] | HtmlTypes['pre'] | HtmlTypes['progress'] | HtmlTypes['q'] | HtmlTypes['ruby'] | HtmlTypes['s'] | HtmlTypes['samp'] | HtmlTypes['script'] | HtmlTypes['section'] | HtmlTypes['select'] | HtmlTypes['small'] | HtmlTypes['span'] | HtmlTypes['strong'] | HtmlTypes['sub'] | HtmlTypes['sup'] | SVGSVGElement | HtmlTypes['table'] | HtmlTypes['template'] | HtmlTypes['textarea'] | HtmlTypes['time'] | HtmlTypes['u'] | HtmlTypes['ul'] | HtmlTypes['var'] | HtmlTypes['video'] | HtmlTypes['wbr'] | string | HtmlTypes['area'] | HtmlTypes['link']
    export type SectioningContent = HtmlTypes['article'] | HtmlTypes['aside'] | HtmlTypes['nav'] | HtmlTypes['section']
    export type HeadingContent = HtmlTypes['h1'] | HtmlTypes['h2'] | HtmlTypes['h3'] | HtmlTypes['h4'] | HtmlTypes['h5'] | HtmlTypes['h6']
    export type PhrasingContent = HtmlTypes['a'] | HtmlTypes['abbr'] | HtmlTypes['audio'] | HtmlTypes['b'] | HtmlTypes['bdi'] | HtmlTypes['bdo'] | HtmlTypes['br'] | HtmlTypes['button'] | HtmlTypes['canvas'] | HtmlTypes['cite'] | HtmlTypes['code'] | HtmlTypes['data'] | HtmlTypes['datalist'] | HtmlTypes['del'] | HtmlTypes['dfn'] | HtmlTypes['em'] | HtmlTypes['embed'] | HtmlTypes['i'] | HtmlTypes['iframe'] | HtmlTypes['img'] | HtmlTypes['input'] | HtmlTypes['ins'] | HtmlTypes['kbd'] | HtmlTypes['label'] | HtmlTypes['map'] | HtmlTypes['mark'] | HtmlTypes['meter'] | HtmlTypes['noscript'] | HtmlTypes['object'] | HtmlTypes['output'] | HtmlTypes['progress'] | HtmlTypes['q'] | HtmlTypes['ruby'] | HtmlTypes['s'] | HtmlTypes['samp'] | HtmlTypes['script'] | HtmlTypes['select'] | HtmlTypes['small'] | HtmlTypes['span'] | HtmlTypes['strong'] | HtmlTypes['sub'] | HtmlTypes['sup'] | SVGSVGElement | HtmlTypes['template'] | HtmlTypes['textarea'] | HtmlTypes['time'] | HtmlTypes['u'] | HtmlTypes['var'] | HtmlTypes['video'] | HtmlTypes['wbr'] | string | HtmlTypes['area'] | HtmlTypes['link']
    export type EmbeddedContent = HtmlTypes['audio'] | HtmlTypes['canvas'] | HtmlTypes['embed'] | HtmlTypes['iframe'] | HtmlTypes['img'] | HtmlTypes['object'] | SVGSVGElement | HtmlTypes['video']
    export type InteractiveContent = HtmlTypes['button'] | HtmlTypes['details'] | HtmlTypes['embed'] | HtmlTypes['iframe'] | HtmlTypes['label'] | HtmlTypes['select'] | HtmlTypes['textarea'] | HtmlTypes['a'] | HtmlTypes['audio'] | HtmlTypes['img'] | HtmlTypes['input'] | HtmlTypes['video']
    export type SectioningRoots = HtmlTypes['blockquote'] | HtmlTypes['body'] | HtmlTypes['details'] | HtmlTypes['dialog'] | HtmlTypes['fieldset'] | HtmlTypes['figure'] | HtmlTypes['td']
    export type FormAssociatedElements = HtmlTypes['button'] | HtmlTypes['fieldset'] | HtmlTypes['input'] | HtmlTypes['label'] | HtmlTypes['object'] | HtmlTypes['output'] | HtmlTypes['select'] | HtmlTypes['textarea'] | HtmlTypes['img']
    export type ListedElements = HtmlTypes['button'] | HtmlTypes['fieldset'] | HtmlTypes['input'] | HtmlTypes['object'] | HtmlTypes['output'] | HtmlTypes['select'] | HtmlTypes['textarea']
    export type SubmittableElements = HtmlTypes['button'] | HtmlTypes['input'] | HtmlTypes['object'] | HtmlTypes['select'] | HtmlTypes['textarea']
    export type ResettableElements = HtmlTypes['input'] | HtmlTypes['output'] | HtmlTypes['select'] | HtmlTypes['textarea']
    export type LabelableElements = HtmlTypes['button'] | HtmlTypes['input'] | HtmlTypes['meter'] | HtmlTypes['output'] | HtmlTypes['progress'] | HtmlTypes['select'] | HtmlTypes['textarea']
    export type ReassociateableElements = HtmlTypes['button'] | HtmlTypes['fieldset'] | HtmlTypes['input'] | HtmlTypes['label'] | HtmlTypes['object'] | HtmlTypes['output'] | HtmlTypes['select'] | HtmlTypes['textarea']
    export type PalpableContent = HtmlTypes['a'] | HtmlTypes['abbr'] | HtmlTypes['address'] | HtmlTypes['article'] | HtmlTypes['aside'] | HtmlTypes['b'] | HtmlTypes['bdi'] | HtmlTypes['bdo'] | HtmlTypes['blockquote'] | HtmlTypes['button'] | HtmlTypes['canvas'] | HtmlTypes['cite'] | HtmlTypes['code'] | HtmlTypes['data'] | HtmlTypes['details'] | HtmlTypes['dfn'] | HtmlTypes['div'] | HtmlTypes['em'] | HtmlTypes['embed'] | HtmlTypes['fieldset'] | HtmlTypes['figure'] | HtmlTypes['footer'] | HtmlTypes['form'] | HtmlTypes['h1'] | HtmlTypes['h2'] | HtmlTypes['h3'] | HtmlTypes['h4'] | HtmlTypes['h5'] | HtmlTypes['h6'] | HtmlTypes['header'] | HtmlTypes['i'] | HtmlTypes['iframe'] | HtmlTypes['img'] | HtmlTypes['ins'] | HtmlTypes['kbd'] | HtmlTypes['label'] | HtmlTypes['main'] | HtmlTypes['map'] | HtmlTypes['mark'] | HtmlTypes['meter'] | HtmlTypes['nav'] | HtmlTypes['object'] | HtmlTypes['output'] | HtmlTypes['p'] | HtmlTypes['pre'] | HtmlTypes['progress'] | HtmlTypes['q'] | HtmlTypes['ruby'] | HtmlTypes['s'] | HtmlTypes['samp'] | HtmlTypes['section'] | HtmlTypes['select'] | HtmlTypes['small'] | HtmlTypes['span'] | HtmlTypes['strong'] | HtmlTypes['sub'] | HtmlTypes['sup'] | SVGSVGElement | HtmlTypes['table'] | HtmlTypes['textarea'] | HtmlTypes['time'] | HtmlTypes['u'] | HtmlTypes['var'] | HtmlTypes['video'] | HtmlTypes['audio'] | HtmlTypes['dl'] | HtmlTypes['input'] | HtmlTypes['ol'] | HtmlTypes['ul'] | string
    export type ScriptSupportingElements = HtmlTypes['script'] | HtmlTypes['template']
}
