import {s} from './s'

export interface SvgTypes {
    a: s.A
    circle: s.Circle
    clipPath: s.ClipPath
    defs: s.Defs
    desc: s.Desc
    ellipse: s.Ellipse
    feBlend: s.FeBlend
    feColorMatrix: s.FeColorMatrix
    feComponentTransfer: s.FeComponentTransfer
    feComposite: s.FeComposite
    feConvolveMatrix: s.FeConvolveMatrix
    feDiffuseLighting: s.FeDiffuseLighting
    feDisplacementMap: s.FeDisplacementMap
    feDistantLight: s.FeDistantLight
    feFlood: s.FeFlood
    feFuncA: s.FeFuncA
    feFuncB: s.FeFuncB
    feFuncG: s.FeFuncG
    feFuncR: s.FeFuncR
    feGaussianBlur: s.FeGaussianBlur
    feImage: s.FeImage
    feMerge: s.FeMerge
    feMergeNode: s.FeMergeNode
    feMorphology: s.FeMorphology
    feOffset: s.FeOffset
    fePointLight: s.FePointLight
    feSpecularLighting: s.FeSpecularLighting
    feSpotLight: s.FeSpotLight
    feTile: s.FeTile
    feTurbulence: s.FeTurbulence
    filter: s.Filter
    foreignObject: s.ForeignObject
    g: s.G
    image: s.Image
    line: s.Line
    linearGradient: s.LinearGradient
    marker: s.Marker
    mask: s.Mask
    metadata: s.Metadata
    path: s.Path
    pattern: s.Pattern
    polygon: s.Polygon
    polyline: s.Polyline
    radialGradient: s.RadialGradient
    rect: s.Rect
    script: s.Script
    stop: s.Stop
    style: s.Style
    svg: s.Svg
    switch: s.Switch
    symbol: s.Symbol
    text: s.Text
    textPath: s.TextPath
    title: s.Title
    tspan: s.Tspan
    use: s.Use
    view: s.View
}
